from enum import Enum

class Mode(Enum):
    ROUND_NEAREST_TIES_EVEN = 0
    ROUND_NEAREST_TIES_AWAY = 1 # NOT CURRENTLY SUPPORTED
    TRUNCATE = 2 # NOT CURRENTLY SUPPORTED
    ROUND_UP = 3 # NOT CURRENTLY SUPPORTED
    ROUND_DOWN = 4 # NOT CURRENTLY SUPPORTED